---
- name: Configure ACI Tenant Policies
  hosts: apic
  connection: local
  gather_facts: False
  vars:
    creds: &login
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      state: "{{ state }}"


  tasks:

  - name: Create Tenants
    cisco.aci.aci_tenant:
      <<: *login
      tenant: "{{ tenant }}"

  - name: Create VRF
    cisco.aci.aci_vrf:
      <<: *login
      vrf: "{{ vrf }}"
      tenant: "{{ tenant }}"
      preferred_group: enabled

  - name: Create BDs
    cisco.aci.aci_bd:
      <<: *login
      tenant: "{{ tenant }}"
      vrf: "{{ vrf }}"
      bd: "{{ item.bd  }}"
    loop:
      "{{ bridge_domains }}"

  - name: Update a subnets scope to private and shared
    cisco.aci.aci_bd_subnet:
      <<: *login
      tenant: "{{ tenant }}"
      bd: "{{ item.bd }}"
      gateway: "{{ item.gw }}"
      mask: 24
      scope: [public]
    loop:
      "{{ bd_subnet }}"

  - name: Create App Profile
    cisco.aci.aci_ap:
      <<: *login
      tenant: "{{ tenant }}"
      ap: "{{ app_profile }}"

  - name: Create EPGs
    cisco.aci.aci_epg:
      <<: *login
      tenant: "{{ tenant }}"
      ap: "{{ app_profile }}"
      epg: "{{ item.epg }}"
      bd: "{{ item.bd }}"
      preferred_group: "{{ pref_group }}"
    loop:
      "{{ epgs }}"

  - name: Bind EPGs to Phys Domain
    cisco.aci.aci_epg_to_domain:
      <<: *login
      tenant: "{{ tenant }}"
      ap: "{{ app_profile }}"
      epg: "{{ item.epg }}"
      domain: "{{ item.domain }}"
      domain_type: phys
    loop:
      "{{ epgs_domains }}"
